@startuml
header "Update player profile"
autonumber
actor User
participant Game
participant Player
participant PlayerWriter
participant Board
database "Player Data" as pd

Game -> User: displayGameMenu()
Game -> User: getUserInput() : int[]
User --> Game: input
Game -> Player: getAllPlayers() : Player[]
Player -> PlayerWriter: getAll() : Player[]
PlayerWriter -> pd: getAll() : Player[]
pd --> PlayerWriter: player array
PlayerWriter --> Player: player array
Player --> Game: player array
Game -> User: getPlayerChoice() : Player
User --> Game: player choice
Game -> User: getName() : String[]
User --> Game: new name
Game -> Player: setName()
Game -> Player: storePlayer()
PlayerWriter-> pd: writeFile()
Game -> User: displayGameMenu()
@enduml
